export const PERMISSIONS = [
  {
    name: "Admin",
    value: "admin",
    actions: [
      { name: "Crear", value: "admin-create" },
      { name: "Editar", value: "admin-update" },
      { name: "Editar contraseña", value: "admin-update-password" },
      { name: "Eliminar", value: "admin-delete" },
      { name: "Eliminar permanente", value: "admin-delete-hard" },
      { name: "Estadisticas", value: "admin-stats" },
      { name: "Restaurar", value: "admin-restore" },
      { name: "Ver", value: "admin-view" },
    ],
  },
  {
    name: "Calendario",
    value: "calendar",
    actions: [{ name: "Ver", value: "calendar-view" }],
  },
  {
    name: "Configuraciones",
    value: "settings",
    actions: [
      { name: "Crear", value: "settings-create" },
      { name: "Editar", value: "settings-update" },
      { name: "Eliminar permanente", value: "settings-delete-hard" },
      { name: "Ver", value: "settings-view" },
    ],
  },
  {
    name: "Pacientes",
    value: "patients",
    actions: [
      { name: "Crear", value: "patient-create" },
      { name: "Editar", value: "patient-update" },
      { name: "Editar contraseña", value: "patient-update-password" },
      { name: "Eliminar", value: "patient-delete" },
      { name: "Eliminar permanente", value: "patient-delete-hard" },
      { name: "Restaurar", value: "patient-restore" },
      { name: "Ver", value: "patient-view" },
      { name: "Ver todos", value: "patient-view" },
    ],
  },
  {
    name: "Permisos",
    value: "permissions",
    actions: [
      { name: "Crear", value: "permissions-create" },
      { name: "Editar", value: "permissions-update" },
      { name: "Eliminar", value: "permissions-delete" },
      { name: "Eliminar permanente", value: "permissions-delete-hard" },
      { name: "Estadisticas", value: "permissions-stats" },
      { name: "Restaurar", value: "permissions-restore" },
      { name: "Ver", value: "permissions-view" },
    ],
  },
  {
    name: "Profesionales",
    value: "professionals",
    actions: [
      { name: "Crear", value: "professional-create" },
      { name: "Editar", value: "professional-update" },
      { name: "Editar contraseña", value: "professional-update-password" },
      { name: "Eliminar", value: "professional-delete" },
      { name: "Eliminar permanente", value: "professional-delete-hard" },
      { name: "Restaurar", value: "professional-restore" },
      { name: "Ver", value: "professional-view" },
    ],
  },
  {
    name: "Roles",
    value: "roles",
    actions: [
      { name: "Crear", value: "roles-create" },
      { name: "Editar", value: "roles-update" },
      { name: "Eliminar", value: "roles-delete" },
      { name: "Eliminar permanente", value: "roles-delete-hard" },
      { name: "Restaurar", value: "roles-restore" },
      { name: "Ver", value: "roles-view" },
    ],
  },
  {
    name: "Turnos",
    value: "events",
    actions: [
      { name: "Crear", value: "events-create" },
      { name: "Editar", value: "events-update" },
      { name: "Eliminar permanente", value: "events-delete-hard" },
      { name: "Enviar notificaciones", value: "events-notify" },
      { name: "Ver", value: "events-view" },
    ],
  },
  {
    name: "Usuarios",
    value: "users",
    actions: [
      { name: "Crear", value: "users-create" },
      { name: "Editar", value: "users-update" },
      { name: "Editar contraseña", value: "users-update-password" },
      { name: "Eliminar", value: "users-delete" },
      { name: "Eliminar permanente", value: "users-delete-hard" },
      { name: "Restaurar", value: "users-restore" },
      { name: "Ver", value: "users-view" },
      { name: "Ver todos", value: "users-view-all" },
    ],
  },
];
